export type Question = {
  id: string;
  chapter: string;
  q: string;
  choices: string[];
  answer: number;
  why: string;
};

export const QUESTIONS: Question[] = [
  {
    id: "q1",
    chapter: "ondes",
    q: "Pour une fréquence et un matériau donnés, quelle onde a la plus petite longueur d'onde ?",
    choices: [
      "L'onde longitudinale",
      "L'onde de compression",
      "L'onde de cisaillement",
      "L'onde de surface",
    ],
    answer: 3,
    why: "Rayleigh / surface : vitesse la plus faible → λ = C/f minimale. Compression et longitudinale, c'est la même chose (OL).",
  },
  {
    id: "q2",
    chapter: "ondes",
    q: "Le déplacement des particules d'une OT est :",
    choices: [
      "Parallèle à la propagation",
      "Perpendiculaire à la propagation",
      "Elliptique dans tout le volume",
      "Nul : seule la pression varie",
    ],
    answer: 1,
    why: "OT = cisaillement : particules ⊥ à la direction de propagation. L'elliptique, c'est Rayleigh, et seulement près de la surface.",
  },
  {
    id: "q3",
    chapter: "ondes",
    q: "Dans un matériau à gros grains, quelles ondes passent le mieux ?",
    choices: ["Les OT", "Les OL", "Les Rayleigh", "Les Lamb"],
    answer: 1,
    why: "À f égale, λ_OL > λ_OT : moins de scattering sur les grains. L'EF s'écroule quand même si le grain est trop gros.",
  },
  {
    id: "q4",
    chapter: "grandeurs",
    q: "Si Z1 = Z2, à l'interface on observe :",
    choices: [
      "Une réflexion totale",
      "Une transmission totale, aucun écho d'interface",
      "Une inversion de phase systématique",
      "Uniquement de l'OT réfractée",
    ],
    answer: 1,
    why: "Er = 0 quand Z1 = Z2. Ce n'est pas « Z grand ⇒ ça passe » : c'est le match d'impédance qui compte.",
  },
  {
    id: "q5",
    chapter: "grandeurs",
    q: "Le coefficient d'intensité de réflexion vaut :",
    choices: [
      "(Z1 − Z2) / (Z1 + Z2)",
      "(Z1 − Z2)² / (Z1 + Z2)²",
      "4 Z1 Z2 / (Z1 + Z2)²",
      "2 Z2 / (Z1 + Z2)",
    ],
    answer: 1,
    why: "L'intensité est au carré. Sans carré, c'est l'amplitude (et encore, avec Z2 − Z1). 4Z1Z2/(Z1+Z2)² = Et.",
  },
  {
    id: "q6",
    chapter: "grandeurs",
    q: "Baisser le gain de 6 dB revient à :",
    choices: [
      "Diviser la puissance par 6",
      "Diviser l'amplitude par 2",
      "Diviser l'amplitude par 6",
      "Diviser l'amplitude par 10",
    ],
    answer: 1,
    why: "ΔdB = 20 log(A2/A1). −6 dB ⇒ A2/A1 = 1/2. −20 dB ⇒ 1/10.",
  },
  {
    id: "q7",
    chapter: "snell",
    q: "sin θ1 / V1 = sin θ2 / V2 est :",
    choices: [
      "Le rapport d'impédance",
      "La zone de Fresnel",
      "La loi de Snell-Descartes",
      "Le coefficient de transmission",
    ],
    answer: 2,
    why: "Snell-Descartes, utilisée pour les angles de réfraction OL et OT.",
  },
  {
    id: "q8",
    chapter: "snell",
    q: "Les OT n'existent pas :",
    choices: [
      "Dans l'acier",
      "Dans le plexiglas",
      "Dans les liquides et les gaz",
      "Au-delà de 5 MHz",
    ],
    answer: 2,
    why: "Pas de résistance au cisaillement → pas d'OT dans l'eau ni l'air.",
  },
  {
    id: "q9",
    chapter: "snell",
    q: "Le premier angle critique correspond à :",
    choices: [
      "OT réfractée à 90°",
      "OL réfractée à 90°",
      "Incidence nulle",
      "Égalité des impédances",
    ],
    answer: 1,
    why: "OL plus rapide → elle rase en premier. Au-delà, le sabot ne couple plus que de l'OT dans l'acier.",
  },
  {
    id: "q10",
    chapter: "snell",
    q: "Un palpeur marqué « 45° » signifie :",
    choices: [
      "Le coin plexi est taillé à 45°",
      "L'OL se réfracte à 45° dans l'acier",
      "L'OT se réfracte à 45° dans l'acier",
      "L'incidence dans l'eau est 45°",
    ],
    answer: 2,
    why: "L'angle marqué = angle de l'OT dans l'acier. Le coin plexi d'un 45° est plutôt ~36°.",
  },
  {
    id: "q11",
    chapter: "champs",
    q: "Dans le champ proche, la pression acoustique :",
    choices: [
      "Décroît de façon monotone",
      "Est nulle",
      "Fluctue fortement (interférences)",
      "Vaut toujours −6 dB",
    ],
    answer: 2,
    why: "Piège classique. La décroissance monotone, c'est Fraunhofer (champ lointain).",
  },
  {
    id: "q12",
    chapter: "champs",
    q: "N₀ = D² / 4λ. Si D diminue, le champ proche :",
    choices: ["S'allonge", "Raccourcit", "Ne change pas", "Devient infini"],
    answer: 1,
    why: "N₀ proportionnel à D². Petit palpeur → Fresnel court, mais divergence plus grande.",
  },
  {
    id: "q13",
    chapter: "champs",
    q: "Le K du premier zéro de divergence (piston circulaire) vaut :",
    choices: ["0,51", "0,87", "1,22", "2,00"],
    answer: 2,
    why: "1,22 = premier zéro. 0,51 = −6 dB. 0,87 = −20 dB.",
  },
  {
    id: "q14",
    chapter: "geometrie",
    q: "Sur une tôle d'épaisseur t, la distance surface d'un ½ skip vaut :",
    choices: ["t / sin θ", "t · tan θ", "t · cos θ", "2 t / tan θ"],
    answer: 1,
    why: "½ skip = t tan θ. Skip complet = 2 t tan θ. Profondeur = P cos θ.",
  },
  {
    id: "q15",
    chapter: "geometrie",
    q: "Un écho d'angle à un parcours P a pour profondeur (avant le ½ skip) :",
    choices: ["P sin θ", "P tan θ", "P cos θ", "P / cos θ"],
    answer: 2,
    why: "d = P cos θ, s = P sin θ. Après le ½ skip, il faut « replier » avec l'épaisseur.",
  },
  {
    id: "q16",
    chapter: "etalonnage",
    q: "Sur une V1, le point d'émergence se mesure sur le rayon :",
    choices: ["25 mm", "50 mm", "100 mm", "300 mm"],
    answer: 2,
    why: "Quart de rond R = 100 mm. PE = 100 − L. (La V2 utilise 25 ou 50 mm.)",
  },
  {
    id: "q17",
    chapter: "etalonnage",
    q: "Tolérance usuelle sur l'angle réel d'un palpeur 45° :",
    choices: ["± 0,5°", "± 2°", "± 5°", "± 10°"],
    answer: 1,
    why: "± 2°. Au-delà, le sabot est usé : on le réforme ou on le reformule dans la FIT.",
  },
  {
    id: "q18",
    chapter: "etalonnage",
    q: "Le rapport signal/bruit se calcule par :",
    choices: ["G1 + G2", "G1 / G2", "G1 − G2", "20 log(G1/G2)"],
    answer: 2,
    why: "G1 (défaut à 20 % HE) moins G2 (herbe à 20 % HE). Le résultat est largement négatif.",
  },
  {
    id: "q19",
    chapter: "avg",
    q: "La méthode AVG estime :",
    choices: [
      "La longueur vraie du défaut",
      "Un diamètre équivalent de TFP",
      "L'angle du palpeur",
      "La rugosité de surface",
    ],
    answer: 1,
    why: "Taille équivalente d'un trou à fond plat, pas la géométrie réelle.",
  },
  {
    id: "q20",
    chapter: "avg",
    q: "Le TCG, c'est :",
    choices: [
      "Une correction de gain en fonction du temps, pour coller les échos de référence à la même hauteur",
      "Un type d'onde de surface",
      "Le nom allemand de l'OT",
      "Un bloc étalon ISO 2400",
    ],
    answer: 0,
    why: "Time Corrected Gain = DAC électronique.",
  },
  {
    id: "q21",
    chapter: "avg",
    q: "La méthode −6 dB sur un défaut plus petit que le faisceau :",
    choices: [
      "Donne la taille vraie",
      "Sous-estime toujours la taille",
      "Surestime souvent (on mesure surtout le faisceau)",
      "Ne s'applique qu'aux OT",
    ],
    answer: 2,
    why: "−6 dB est faite pour les réflecteurs plus grands que le faisceau. Sinon → AVG / DAC.",
  },
  {
    id: "q22",
    chapter: "forge",
    q: "Les flocons dans un forgeage :",
    choices: [
      "Sont exclusivement des défauts de surface",
      "Viennent d'un excès d'hydrogène et peuvent disparaître au reforgeage",
      "Sont des retassures de tête de lingot",
      "N'apparaissent que pendant la trempe",
    ],
    answer: 1,
    why: "H2, délai de plusieurs jours, décohésion interne. Tapures = surface / trempe. Retassures = solidification.",
  },
  {
    id: "q23",
    chapter: "forge",
    q: "Le contrôle US des pièces forgées ferritiques relève de :",
    choices: ["NF EN ISO 10228-3", "NF EN 10228-3", "NF EN 10160", "ISO 9712"],
    answer: 1,
    why: "EN 10228-3, pas une ISO. 10160 = plats. 9712 = personnel.",
  },
  {
    id: "q24",
    chapter: "forge",
    q: "Sur un brut de forge, on privilégie :",
    choices: [
      "Un palpeur d'angle 70° sec",
      "Une membrane souple et de l'huile",
      "Un palpeur immersé sans couplant",
      "Une fréquence 15 MHz",
    ],
    answer: 1,
    why: "La membrane épouse la peau d'orange. Fréquence haute = suicide sur brut.",
  },
  {
    id: "q25",
    chapter: "fit",
    q: "Dans une FIT destinée à un niveau 1, les critères d'acceptation :",
    choices: [
      "Peuvent être laissés à l'appréciation de l'opérateur",
      "Doivent être chiffrés (ou renvoyés explicitement au sujet / code)",
      "Sont facultatifs si on joint une photo",
      "Relèvent uniquement du niveau 3",
    ],
    answer: 1,
    why: "Le N2 décide et écrit. Le N1 exécute. Rien d'implicite.",
  },
  {
    id: "q26",
    chapter: "fit",
    q: "Recouvrement et vitesse de sondage typiques d'un 100 % plaques :",
    choices: [
      "0 % et 500 mm/s",
      "10 % et 150 mm/s",
      "50 % et 10 mm/s",
      "100 % et 1 m/s",
    ],
    answer: 1,
    why: "10 % de recouvrement, 150 mm/s : valeurs de la FIT-type EN 10160 du cahier.",
  },
  {
    id: "q27",
    chapter: "grandeurs",
    q: "Interface acier / air :",
    choices: [
      "Transmission quasi totale",
      "Réflexion quasi totale",
      "Uniquement de l'OT transmise",
      "Aucun écho possible",
    ],
    answer: 1,
    why: "Z_air ≈ 0. C'est pour ça qu'un défaut débouchant « mange » l'écho de fond.",
  },
  {
    id: "q28",
    chapter: "ondes",
    q: "Les ondes de Lamb sont surtout utilisées pour :",
    choices: [
      "Les pièces massives de forge",
      "Les tôles minces (ordre ≤ 3 mm)",
      "Les contrôles en immersion profonde",
      "Remplacer les OT au-delà du 2e critique",
    ],
    answer: 1,
    why: "Modes guidés de plaque mince. Sans courbe, on prend l'angle d'amplitude max.",
  },
];
