export type Question = {
  id: string;
  chapter: string;
  q: string;
  choices: string[];
  answer: number;
  why: string;
};

export const QUESTIONS: Question[] = [
  {
    id: "q1",
    chapter: "ondes",
    q: "Parmi les ondes volumiques OL, OT et l'onde de surface de Rayleigh, laquelle a la plus petite longueur d'onde à fréquence et matériau identiques ?",
    choices: [
      "L'onde longitudinale (OL)",
      "L'onde transversale (OT)",
      "L'onde de surface de Rayleigh",
      "Elles ont toutes la même longueur d'onde",
    ],
    answer: 2,
    why: "Pour un matériau donné, la vitesse de Rayleigh est inférieure à celle de l'OT, elle-même inférieure à celle de l'OL : λ = C/f est donc la plus courte pour Rayleigh. OL et onde de compression désignent le même mode."
  },
  {
    id: "q2",
    chapter: "ondes",
    q: "Le déplacement des particules d'une OT est :",
    choices: [
      "Parallèle à la propagation",
      "Perpendiculaire à la propagation",
      "Elliptique dans tout le volume",
      "Nul : seule la pression varie",
    ],
    answer: 1,
    why: "OT = cisaillement : particules ⊥ à la direction de propagation. L'elliptique, c'est Rayleigh, et seulement près de la surface.",
  },
  {
    id: "q3",
    chapter: "ondes",
    q: "Dans un matériau à gros grains, quelles ondes passent le mieux ?",
    choices: ["Les OT", "Les OL", "Les Rayleigh", "Les Lamb"],
    answer: 1,
    why: "À f égale, λ_OL > λ_OT : moins de scattering sur les grains. L'EF s'écroule quand même si le grain est trop gros.",
  },
  {
    id: "q4",
    chapter: "grandeurs",
    q: "Si Z1 = Z2, à l'interface on observe :",
    choices: [
      "Une réflexion totale",
      "Une transmission totale, aucun écho d'interface",
      "Une inversion de phase systématique",
      "Uniquement de l'OT réfractée",
    ],
    answer: 1,
    why: "Er = 0 quand Z1 = Z2. Ce n'est pas « Z grand ⇒ ça passe » : c'est le match d'impédance qui compte.",
  },
  {
    id: "q5",
    chapter: "grandeurs",
    q: "Le coefficient d'intensité de réflexion vaut :",
    choices: [
      "(Z1 − Z2) / (Z1 + Z2)",
      "(Z1 − Z2)² / (Z1 + Z2)²",
      "4 Z1 Z2 / (Z1 + Z2)²",
      "2 Z2 / (Z1 + Z2)",
    ],
    answer: 1,
    why: "L'intensité est au carré. Sans carré, c'est l'amplitude (et encore, avec Z2 − Z1). 4Z1Z2/(Z1+Z2)² = Et.",
  },
  {
    id: "q6",
    chapter: "grandeurs",
    q: "Baisser le gain de 6 dB revient à :",
    choices: [
      "Diviser la puissance par 6",
      "Diviser l'amplitude par 2",
      "Diviser l'amplitude par 6",
      "Diviser l'amplitude par 10",
    ],
    answer: 1,
    why: "ΔdB = 20 log(A2/A1). −6 dB ⇒ A2/A1 = 1/2. −20 dB ⇒ 1/10.",
  },
  {
    id: "q7",
    chapter: "snell",
    q: "sin θ1 / V1 = sin θ2 / V2 est :",
    choices: [
      "Le rapport d'impédance",
      "La zone de Fresnel",
      "La loi de Snell-Descartes",
      "Le coefficient de transmission",
    ],
    answer: 2,
    why: "Snell-Descartes, utilisée pour les angles de réfraction OL et OT.",
  },
  {
    id: "q8",
    chapter: "snell",
    q: "Les OT n'existent pas :",
    choices: [
      "Dans l'acier",
      "Dans le plexiglas",
      "Dans les liquides et les gaz",
      "Au-delà de 5 MHz",
    ],
    answer: 2,
    why: "Pas de résistance au cisaillement → pas d'OT dans l'eau ni l'air.",
  },
  {
    id: "q9",
    chapter: "snell",
    q: "Le premier angle critique correspond à :",
    choices: [
      "OT réfractée à 90°",
      "OL réfractée à 90°",
      "Incidence nulle",
      "Égalité des impédances",
    ],
    answer: 1,
    why: "OL plus rapide → elle atteint 90° au premier angle critique. Entre les deux angles critiques, il n'y a plus d'OL volumique réfractée ; l'OT peut encore être réfractée. Au-delà du second, le modèle volumique classique ne donne plus d'OT réfractée non rasante ; des composantes de surface peuvent dépendre de la configuration.",
  },
  {
    id: "q10",
    chapter: "snell",
    q: "Un palpeur marqué « 45° » signifie :",
    choices: [
      "Le coin plexi est taillé à 45°",
      "L'OL se réfracte à 45° dans l'acier",
      "L'OT se réfracte à 45° dans l'acier",
      "L'incidence dans l'eau est 45°",
    ],
    answer: 2,
    why: "L'angle marqué = angle de l'OT dans l'acier. Le coin plexi d'un 45° est plutôt ~36°.",
  },
  {
    id: "q11",
    chapter: "champs",
    q: "Dans le champ proche, la pression acoustique :",
    choices: [
      "Décroît de façon monotone",
      "Est nulle",
      "Fluctue fortement (interférences)",
      "Vaut toujours −6 dB",
    ],
    answer: 2,
    why: "Piège classique. La décroissance monotone, c'est Fraunhofer (champ lointain).",
  },
  {
    id: "q12",
    chapter: "champs",
    q: "N₀ = D² / 4λ. Si D diminue, le champ proche :",
    choices: ["S'allonge", "Raccourcit", "Ne change pas", "Devient infini"],
    answer: 1,
    why: "N₀ proportionnel à D². Petit palpeur → Fresnel court, mais divergence plus grande.",
  },
  {
    id: "q13",
    chapter: "champs",
    q: "Le K du premier zéro de divergence (piston circulaire) vaut :",
    choices: ["0,51", "0,87", "1,22", "2,00"],
    answer: 2,
    why: "1,22 = premier zéro. 0,51 = −6 dB. 0,87 = −20 dB.",
  },
  {
    id: "q14",
    chapter: "geometrie",
    q: "Sur une tôle d'épaisseur t, la distance surface d'un ½ skip vaut :",
    choices: ["t / sin θ", "t · tan θ", "t · cos θ", "2 t / tan θ"],
    answer: 1,
    why: "½ skip = t tan θ. Skip complet = 2 t tan θ. Profondeur = P cos θ.",
  },
  {
    id: "q15",
    chapter: "geometrie",
    q: "Un écho d'angle à un parcours P a pour profondeur (avant le ½ skip) :",
    choices: ["P sin θ", "P tan θ", "P cos θ", "P / cos θ"],
    answer: 2,
    why: "d = P cos θ, s = P sin θ. Après le ½ skip, il faut « replier » avec l'épaisseur.",
  },
  {
    id: "q16",
    chapter: "etalonnage",
    q: "Sur une V1, le point d'émergence se mesure sur le rayon :",
    choices: ["25 mm", "50 mm", "100 mm", "300 mm"],
    answer: 2,
    why: "Quart de rond R = 100 mm. PE = 100 − L. (La V2 utilise 25 ou 50 mm.)",
  },
  {
    id: "q17",
    chapter: "etalonnage",
    q: "Pour vérifier l'angle réel d'un palpeur 45°, la tolérance à appliquer est :",
    choices: [
      "Toujours ± 0,5°",
      "Celle fixée par la norme ou la procédure applicable",
      "Toujours ± 5°",
      "Toujours ± 10°",
    ],
    answer: 1,
    why: "La tolérance dépend du référentiel applicable. Une valeur d'exemple de formation ne doit pas être mémorisée comme une tolérance universelle.",
  },
  {
    id: "q18",
    chapter: "etalonnage",
    q: "Dans la convention de mesure de cet exercice, l'écart de gain entre le signal et le bruit se calcule par :",
    choices: ["G1 + G2", "G1 / G2", "G1 − G2", "20 log(G1/G2)"],
    answer: 2,
    why: "Ici ΔG = G1 − G2, avec G1 le gain nécessaire pour le signal et G2 celui nécessaire pour amener le bruit à la même hauteur. Selon la convention utilisée, une marge S/B peut ensuite être exprimée comme une valeur positive.",
  },
  {
    id: "q19",
    chapter: "avg",
    q: "La méthode AVG estime :",
    choices: [
      "La longueur vraie du défaut",
      "Un diamètre équivalent de TFP",
      "L'angle du palpeur",
      "La rugosité de surface",
    ],
    answer: 1,
    why: "Taille équivalente d'un trou à fond plat, pas la géométrie réelle.",
  },
  {
    id: "q20",
    chapter: "avg",
    q: "Le TCG, c'est :",
    choices: [
      "Une correction de gain en fonction du temps, pour coller les échos de référence à la même hauteur",
      "Un type d'onde de surface",
      "Le nom allemand de l'OT",
      "Un bloc étalon ISO 2400",
    ],
    answer: 0,
    why: "Le TCG augmente le gain en fonction du temps pour compenser la perte d'amplitude avec la distance. Il poursuit le même objectif que la DAC, mais sous forme de correction électronique.",
  },
  {
    id: "q21",
    chapter: "avg",
    q: "La méthode −6 dB sur un défaut plus petit que le faisceau :",
    choices: [
      "Donne la taille vraie",
      "Sous-estime toujours la taille",
      "Surestime souvent (on mesure surtout le faisceau)",
      "Ne s'applique qu'aux OT",
    ],
    answer: 2,
    why: "−6 dB est faite pour les réflecteurs plus grands que le faisceau. Sinon → AVG / DAC.",
  },
  {
    id: "q22",
    chapter: "forge",
    q: "Les flocons dans un forgeage sont :",
    choices: [
      "Exclusivement des défauts de surface",
      "Des discontinuités internes liées à l'hydrogène, pouvant apparaître après un délai",
      "Des retassures de tête de lingot",
      "Des défauts qui apparaissent uniquement pendant la trempe",
    ],
    answer: 1,
    why: "Les flocons sont des discontinuités internes associées à l'hydrogène et peuvent être détectés après un délai. Ils ne doivent pas être présentés comme des défauts éliminables simplement par reforgeage."
  },
  {
    id: "q23",
    chapter: "forge",
    q: "Le contrôle US des pièces forgées ferritiques relève de :",
    choices: ["NF EN ISO 10228-3", "NF EN 10228-3", "NF EN 10160", "ISO 9712"],
    answer: 1,
    why: "EN 10228-3, pas une ISO. 10160 = plats. 9712 = personnel.",
  },
  {
    id: "q24",
    chapter: "forge",
    q: "Sur un brut de forge, quelle approche peut améliorer le couplage et limiter l'influence de la rugosité ?" 
    choices: [
      "Un palpeur d'angle 70° sec",
      "Une membrane souple avec un couplant adapté",
      "Un palpeur immergé sans couplant",
      "Une fréquence élevée choisie sans tenir compte du grain",
    ],
    answer: 1,
    why: "Une membrane souple peut mieux épouser une surface irrégulière et un couplant adapté améliore le transfert acoustique. La fréquence doit être choisie selon l'état de surface, le matériau, le grain, l'atténuation et la procédure ; aucune fréquence unique n'est universelle.",
  },
  {
    id: "q25",
    chapter: "fit",
    q: "Dans une FIT destinée à un niveau 1, les critères d'acceptation :",
    choices: [
      "Peuvent être laissés à l'appréciation de l'opérateur",
      "Doivent être chiffrés (ou renvoyés explicitement au sujet / code)",
      "Sont facultatifs si on joint une photo",
      "Relèvent uniquement du niveau 3",
    ],
    answer: 1,
    why: "Le N2 décide et écrit. Le N1 exécute. Rien d'implicite.",
  },
  {
    id: "q26",
    chapter: "fit",
    q: "Dans une FIT de contrôle à 100 % d'une plaque, le recouvrement et la vitesse de balayage sont :",
    choices: [
      "Toujours 0 % et 500 mm/s",
      "Des paramètres à fixer explicitement dans la procédure, selon la norme, le produit et le sujet",
      "Toujours 50 % et 10 mm/s",
      "Toujours 100 % et 1 m/s",
    ],
    answer: 1,
    why: "Une FIT doit définir les conditions de balayage applicables. Une valeur rencontrée dans un exemple de formation ne doit pas être mémorisée comme une limite universelle."
  },
  {
    id: "q27",
    chapter: "grandeurs",
    q: "Interface acier / air :",
    choices: [
      "Transmission quasi totale",
      "Réflexion quasi totale",
      "Uniquement de l'OT transmise",
      "Aucun écho possible",
    ],
    answer: 1,
    why: "Z_air ≈ 0. C'est pour ça qu'un défaut débouchant « mange » l'écho de fond.",
  },
  {
    id: "q28",
    chapter: "ondes",
    q: "Les ondes de Lamb sont :",
    choices: [
      "Des ondes volumiques réservées aux pièces massives",
      "Des modes guidés dans des plaques ou parois, dont le comportement dépend notamment de f × épaisseur",
      "Des OT qui apparaissent automatiquement après le 2e angle critique",
      "Des ondes de surface de Rayleigh, avec une autre appellation",
    ],
    answer: 1,
    why: "Les modes de Lamb sont guidés par une plaque/paroi et peuvent être symétriques ou antisymétriques (par exemple S0/A0). Il n'existe pas de seuil universel de 3 mm : le produit fréquence × épaisseur et le mode considéré comptent."
  },
];
