/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as FormulaireRouteImport } from './routes/formulaire'
import { Route as GlossaireRouteImport } from './routes/glossaire'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ChapitreSlugRouteImport } from './routes/chapitre.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaireRoute = FormulaireRouteImport.update({
  id: '/formulaire',
  path: '/formulaire',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaireRoute = GlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapitreSlugRoute = ChapitreSlugRouteImport.update({
  id: '/chapitre/$slug',
  path: '/chapitre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/formulaire': typeof FormulaireRoute
  '/glossaire': typeof GlossaireRoute
  '/quiz': typeof QuizRoute
  '/chapitre/$slug': typeof ChapitreSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/formulaire': typeof FormulaireRoute
  '/glossaire': typeof GlossaireRoute
  '/quiz': typeof QuizRoute
  '/chapitre/$slug': typeof ChapitreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/formulaire': typeof FormulaireRoute
  '/glossaire': typeof GlossaireRoute
  '/quiz': typeof QuizRoute
  '/chapitre/$slug': typeof ChapitreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/formulaire'
    | '/glossaire'
    | '/quiz'
    | '/chapitre/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/formulaire'
    | '/glossaire'
    | '/quiz'
    | '/chapitre/$slug'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/formulaire'
    | '/glossaire'
    | '/quiz'
    | '/chapitre/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  FormulaireRoute: typeof FormulaireRoute
  GlossaireRoute: typeof GlossaireRoute
  QuizRoute: typeof QuizRoute
  ChapitreSlugRoute: typeof ChapitreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaire': {
      id: '/formulaire'
      path: '/formulaire'
      fullPath: '/formulaire'
      preLoaderRoute: typeof FormulaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossaire': {
      id: '/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof GlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapitre/$slug': {
      id: '/chapitre/$slug'
      path: '/chapitre/$slug'
      fullPath: '/chapitre/$slug'
      preLoaderRoute: typeof ChapitreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  FormulaireRoute: FormulaireRoute,
  GlossaireRoute: GlossaireRoute,
  QuizRoute: QuizRoute,
  ChapitreSlugRoute: ChapitreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
